---
title: Personal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    hidden: false
name: Zach Zhao
bio: live and learn
description: My personal corner on the internet
external-image: false
picture: assets/images/profile.jpg
resume: true
resume-external: false
resume-url: assets/documents/pre-resume.pdf
url: https://zachzhao.dev
permalink: "/:title/"
disqus:
  shortname: mydisqus
  categories: 
facebook: 
twitter: thezachzhao
github: zeyuzhao
linkedin: zachzzhao
email: thezachzhao@gmail.com
authors:
  zachzhao:
    name: Zach Zhao
    bio: live and learn
    external-image: false
    picture: assets/images/profile.jpg
    twitter: thezachzhao
width: normal
pagination:
  enabled: false
  sort_reverse: true
  title: ":title"
  per_page: 5
  permalink: "/:num/"
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
- blog
show-author: true
animation: true
analytics-google: UA-163893868-1
plugins:
- jekyll-seo-tag
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-admin
- jekyll-paginate-v2
jekyll-mentions:
  base_url: https://github.com
compress_html:
  ignore:
    envs:
    - development
    - stage
exclude:
- travis.sh
- Rakefile
- README.md
- Gemfile
- Gemfile.lock
- FAQ.md
- node_modules
- vendor
- archive
