name: Update User Settings
on:
  push:
    branches:
      - master

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Create request
      - uses: octokit/request-action@v2.x
        name: Update CNAME and source
        id: update_site_cname
        with:
          route: PUT /repos/:repo/pages
          repository: ${{ github.repository }}
          cname: "zachzhao.dev"
          source: "gh-pages /"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ github.GITHUB_ACTOR }}
