name: Jekyll Deploy
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-TEST2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-GEMS-
      - name: Build & Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_REPOSITORY: '${{ github.GITHUB_REPOSITORY }}'
          GITHUB_ACTOR: '${{ github.GITHUB_ACTOR }}'
        uses: zeyuzhao/jekyll-deploy-gh-pages@master
